---
- name: Deploy SSH Public Key
  hosts: all
  become: true
  tasks:
    - name: Ensure host is in known_hosts
      known_hosts:
        path: ~/.ssh/known_hosts
        name: "{{ inventory_hostname }}"
        key:  "{{ lookup('pipe', 'ssh-keyscan -H ' + inventory_hostname) }}"

    - name: Ensure SSH key is present
      authorized_key:
        user: root
        state: present
        key: '{{ item }}'
      with_file:
        - ~/.ssh/id_rsa.pub
