---
- name: Deploy SSH Public Key
  hosts: all
  become: true
  tasks:
    - name: Ensure host is in known_hosts
      known_hosts:
        path: ~/.ssh/known_hosts
        name: "{{ ansible_host }}"
        key: "{{ lookup( 'pipe', 'ssh-keyscan -H ' + ansible_host) }}"

    - name: Ensure SSH key is present
      authorized_key:
        user: vagrant  # Change selon ton besoin (ex: vagrant)
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
